<script type="text/javascript" src="resources/js/libs/jquery.min.js"></script>
<script type="text/javascript" src="resources/js/libs/popper.min.js"></script>
<script type="text/javascript" src="resources/js/libs/utils.js"></script>
<script type="text/javascript" src="resources/external/bootstrap.js"></script>
<script type="text/javascript" src="resources/js/vars/variables.js"></script>
<script type="text/javascript" src="resources/js/vars/game.js"></script>
<script type="text/javascript" src="resources/js/vars/grids.js"></script>
<script type="text/javascript" src="resources/js/libs/grid-support.js"></script>
<script type="text/javascript" src="resources/js/funcs/init-grid.js"></script>
<script type="text/javascript" src="resources/js/funcs/instructions.js"></script>
<script type="text/javascript" src="resources/js/funcs/validate.js"></script>
<script type="text/javascript" src="resources/external/handlebars.runtime-v4.0.12.js"></script>
<script type="text/javascript" src="resources/js/vars/templates.js"></script>
<script type="text/javascript" src="resources/js/main.js"></script>
